package pengobatanifrina;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Satria
 */
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import pengobatanifrina.javaconnect;
public class dokter_form extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs =null;
    PreparedStatement stmnt = null;
    /**
     * Creates new form dokter_form
     */
    public dokter_form() {
        initComponents();
        conn = javaconnect.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaDokter = new javax.swing.JLabel();
        keahlian = new javax.swing.JLabel();
        noHP = new javax.swing.JLabel();
        addDokter = new javax.swing.JButton();
        txt_namaDokter = new javax.swing.JTextField();
        txt_keahlian = new javax.swing.JTextField();
        txt_noHP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namaDokter.setText("Nama Dokter");

        keahlian.setText("Keahlian");

        noHP.setText("Nomor HP");

        addDokter.setText("Tambah Dokter");
        addDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDokterActionPerformed(evt);
            }
        });

        txt_namaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaDokterActionPerformed(evt);
            }
        });

        txt_noHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noHPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDokter)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaDokter)
                            .addComponent(keahlian)
                            .addComponent(noHP))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_keahlian)
                            .addComponent(txt_namaDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txt_noHP))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaDokter)
                    .addComponent(txt_namaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keahlian)
                    .addComponent(txt_keahlian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noHP)
                    .addComponent(txt_noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addDokter)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        addDokter.getAccessibleContext().setAccessibleName("addDokter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDokterActionPerformed
         String sqlCommand = "INSERT INTO dokter (dokter_name,dokter_spesialis,no_telp)VALUES(?,?,?)";
        try {
            stmnt = conn.prepareStatement(sqlCommand);
        } catch (SQLException ex) {
            Logger.getLogger(dokter_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmnt.setString(1,txt_namaDokter.getText());
            stmnt.setString(2,txt_keahlian.getText());
            stmnt.setString(3,txt_noHP.getText());
            //use stmnt.executeQuery(); for reading database
            //use stmnt.executeUpdate(); for Insert, Update, Delete
            stmnt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(dokter_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addDokterActionPerformed

    private void txt_noHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noHPActionPerformed

    private void txt_namaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dokter_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dokter_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dokter_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dokter_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dokter_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDokter;
    private javax.swing.JLabel keahlian;
    private javax.swing.JLabel namaDokter;
    private javax.swing.JLabel noHP;
    private javax.swing.JTextField txt_keahlian;
    private javax.swing.JTextField txt_namaDokter;
    private javax.swing.JTextField txt_noHP;
    // End of variables declaration//GEN-END:variables
}
